kind: pipeline
name: default

workspace:
  path: Prusa-Firmware

steps:
  - name: tests
    image: vertigo235/fw-build
    commands:
      - bash -x test.sh
    when:
      event: 
        - push
        - tag
        - pull_request
  
  - name: build-a-bear
    image: vertigo235/fw-build
    environment:
      BUILD_TYPE: GOLD
    commands:
      - chmod +x PF-build.sh
      - chmod +x lang/config.sh
      - chmod +x lang/fw-clean.sh
      - chmod +x lang/lang-clean.sh
      - sed -i -e 's/#define FW_COMMIT_NR   [0-9]*/#define FW_COMMIT_NR  '"$DRONE_BUILD_STARTED"'/' Firmware/Configuration.h
      - bash -x PF-build.sh Bear_Cal_FW_MK3S-EINSy10a.h ALL $BUILD_TYPE
      - bash -x PF-build.sh Bear_Cal_FW_MK25S-RAMBo10a.h ALL $BUILD_TYPE
      - bash -x PF-build.sh Bear_Cal_FW_MK25S-RAMBo13a.h ALL $BUILD_TYPE
      - bash -x PF-build.sh Bear_Cal_FW_MK3S_Hemera-EINSy10a.h ALL $BUILD_TYPE
      - bash -x PF-build.sh Bear_Cal_FW_MK25S_Hemera-RAMBo13a.h ALL $BUILD_TYPE
      - bash -x PF-build.sh Bear_Cal_FW_MK25S_Hemera-RAMBo10a.h ALL $BUILD_TYPE
    when:
      event:
       - push
       - tag
       - pull_request
  
  - name: prepare-hex
    image: vertigo235/fw-build
    commands:
      - cd $DRONE_WORKSPACE
      - mkdir out
      - mkdir fileshare
      - cd $DRONE_WORKSPACE_BASE/PF-build-hex
      - mv `find -name "*.zip"` $DRONE_WORKSPACE/out
      - mv `find -name "*.hex"` $DRONE_WORKSPACE/out
      - cd $DRONE_WORKSPACE/out
      - unzip \*.zip
      - rm *.zip
      - cd $DRONE_WORKSPACE
      - bash rename_and_zip.sh
      - cd $DRONE_WORKSPACE/fileshare
      - zip -q -j bearcal_fw_$(git rev-parse --short HEAD).zip $DRONE_WORKSPACE/out/*.*
    depends_on:
      - build-a-bear    
    when:
      event:
       - tag
       - push
    
  - name: fileio
    image: vertigo235/fw-build:1
    failure: ignore
    commands:
      - cd $DRONE_WORKSPACE/fileshare
      - curl -F "file=@bearcal_fw_$(git rev-parse --short HEAD).zip" https://file.io
      - echo
    when:
      event:
      - push
      - tag
      - pull_request
    depends_on:
      - prepare-hex

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github-token
      prerelease: true
      draft: true    
      checksum: md5
      files: 
        - out/*.*
    when:
      event: 
        - tag